export { Footer } from './Footer';
export { GuaranteesSection } from './GuaranteesSection';
export { Header } from './Header';
export { HeroSection } from './HeroSection';
export { HistorySection } from './HistorySection';
export { RolesSection } from './RolesSection';
export { StagesSection } from './StagesSection';
export { FAQSection } from './FAQSection';
export { ContactFormSection } from './ContactFormSection';
